services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='minhno123'
      - POSTGRES_DB='postgres'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
